server:
  port: 8080
spring:
  application:
    name: kakaopay-sprinkle
  profiles:
    active: local
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    kr.per.james.kakaopay.sprinkling: debug
